name: Deploy via SSH

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.7.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run commands on Droplet
        run: |
          ssh -o StrictHostKeyChecking=no root@143.198.59.151 << 'EOF'
            cd ~/claude
            git pull origin main
            docker-compose down
            docker-compose up -d --build
          EOF
